# file Makefile.inc
# make file paths for Wzem combined daemon, release wzemcmbd_arty(linux (ubt_x86_64) cross-compilation)
# author Catherine Johnson
# date created: 21 Sep 2020
# modified: 21 Sep 2020

SRCROOT = ${WHIZROOT}/src
LIBROOT = ${WHIZROOT}/lib
BINROOT = ${WHIZROOT}/bin

