# file Makefile.inc
# make file paths for Wzem daemon, release wzemd_ungenio
# author Alexander Wirthmueller
# date created: 4 Jun 2020
# modified: 4 Jun 2020

SRCROOT = /Users/mpsitech/src
LIBROOT = /Users/mpsitech/lib
BINROOT = /Users/mpsitech/bin

