# file Makefile.inc
# make file paths for Wzem combined daemon, release wzemcmbd_zedboard(jack (x86ubt) cross-compilation)
# author Alexander Wirthmueller
# date created: 4 Jun 2020
# modified: 4 Jun 2020

SRCROOT = /home/root/src
LIBROOT = /home/root/lib
BINROOT = /home/root/bin

