# file Makefile.inc
# make file paths for Wzem combined daemon, release wzemcmbd_awscyg
# author Alexander Wirthmueller
# date created: 4 Jun 2020
# modified: 4 Jun 2020

SRCROOT = /home/Administrator/src
LIBROOT = /home/Administrator/lib
BINROOT = /home/Administrator/bin

