# file Makefile.inc
# make file paths for Wzem combined daemon, release wzemcmbd_ssv(jack (x86ubt) cross-compilation)
# author Alexander Wirthmueller
# date created: 4 Jun 2020
# modified: 4 Jun 2020

SRCROOT = /root/src
LIBROOT = /root/lib
BINROOT = /root/bin

