# file Makefile.inc
# make file paths for Wzem combined daemon, release wzemcmbd_awsubt
# author Alexander Wirthmueller
# date created: 4 Jun 2020
# modified: 4 Jun 2020

SRCROOT = /home/ubuntu/src
LIBROOT = /home/ubuntu/lib
BINROOT = /home/ubuntu/bin

